FROM registry.access.redhat.com/ubi9/go-toolset:1.25.8@sha256:75ecb48dfaec6655bd589091902e3b9328c300befba34cb06fc5e7323099e17d AS builder
ARG TARGETOS=linux
ARG TARGETARCH
ARG CGO_ENABLED=1
# BUILD_TYPE=CI for hermetic konflux build (downstream)
ARG BUILD_TYPE

WORKDIR /opt/app-root/src

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY api/ api/
COPY internal/ internal/

# Obtain the batch-gateway Helm chart into /tmp/batch-gateway-chart.
COPY Makefile ./

RUN mkdir -p -m 777 /tmp/batch-gateway-chart
# For all the crazy permisison denies
COPY --chown=1001:0 Dockerfile prefetched-charts* /tmp/batch-gateway-chart/

RUN if [ "${BUILD_TYPE}" != "CI" ]; then \
        make fetch-batch-gateway && \
        cp -r batch-gateway/charts/batch-gateway /tmp/batch-gateway-chart; \
    fi

RUN mkdir -p bin && \
CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
GOEXPERIMENT=strictfipsruntime \
go build -a -o bin/manager ./cmd/

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7@sha256:907b68736aa798b2d38255b7aa070b2a70acb90803864a40f05d0ec47556ddd0
WORKDIR /
COPY --from=builder /opt/app-root/src/bin/manager /manager
COPY --from=builder /tmp/batch-gateway-chart /charts/batch-gateway/
RUN rm -f /charts/batch-gateway/Dockerfile

USER 1001:1001
ENTRYPOINT ["/manager"]
