apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch-gateway-operator
  namespace: system
  labels:
    app.kubernetes.io/name: batch-gateway-operator
    app.kubernetes.io/managed-by: kustomize
