//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMDConfig) DeepCopyInto(out *AIMDConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMDConfig.
func (in *AIMDConfig) DeepCopy() *AIMDConfig {
	if in == nil {
		return nil
	}
	out := new(AIMDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerConfigSpec) DeepCopyInto(out *APIServerConfigSpec) {
	*out = *in
	if in.BatchAPI != nil {
		in, out := &in.BatchAPI, &out.BatchAPI
		*out = new(BatchAPIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FileAPI != nil {
		in, out := &in.FileAPI, &out.FileAPI
		*out = new(FileAPIConfig)
		**out = **in
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerConfigSpec.
func (in *APIServerConfigSpec) DeepCopy() *APIServerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(APIServerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerSpec) DeepCopyInto(out *APIServerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(APIServerConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerSpec.
func (in *APIServerSpec) DeepCopy() *APIServerSpec {
	if in == nil {
		return nil
	}
	out := new(APIServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncGCPPubSubSpec) DeepCopyInto(out *AsyncGCPPubSubSpec) {
	*out = *in
	if in.TopicsConfig != nil {
		in, out := &in.TopicsConfig, &out.TopicsConfig
		*out = make([]AsyncTopicConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncGCPPubSubSpec.
func (in *AsyncGCPPubSubSpec) DeepCopy() *AsyncGCPPubSubSpec {
	if in == nil {
		return nil
	}
	out := new(AsyncGCPPubSubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncModelServerMonitorSpec) DeepCopyInto(out *AsyncModelServerMonitorSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncModelServerMonitorSpec.
func (in *AsyncModelServerMonitorSpec) DeepCopy() *AsyncModelServerMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(AsyncModelServerMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncProcessorSpec) DeepCopyInto(out *AsyncProcessorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.InferenceGateway != nil {
		in, out := &in.InferenceGateway, &out.InferenceGateway
		*out = new(InferenceGatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(AsyncRedisSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCPPubSub != nil {
		in, out := &in.GCPPubSub, &out.GCPPubSub
		*out = new(AsyncGCPPubSubSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerPools != nil {
		in, out := &in.WorkerPools, &out.WorkerPools
		*out = make([]AsyncWorkerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(AsyncTLSSpec)
		**out = **in
	}
	if in.TransformConfig != nil {
		in, out := &in.TransformConfig, &out.TransformConfig
		*out = new(AsyncTransformConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelServerMonitor != nil {
		in, out := &in.ModelServerMonitor, &out.ModelServerMonitor
		*out = new(AsyncModelServerMonitorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncProcessorSpec.
func (in *AsyncProcessorSpec) DeepCopy() *AsyncProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(AsyncProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncQueueConfig) DeepCopyInto(out *AsyncQueueConfig) {
	*out = *in
	if in.GateParams != nil {
		in, out := &in.GateParams, &out.GateParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncQueueConfig.
func (in *AsyncQueueConfig) DeepCopy() *AsyncQueueConfig {
	if in == nil {
		return nil
	}
	out := new(AsyncQueueConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncRedisSpec) DeepCopyInto(out *AsyncRedisSpec) {
	*out = *in
	if in.PollIntervalMs != nil {
		in, out := &in.PollIntervalMs, &out.PollIntervalMs
		*out = new(int32)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.GateParams != nil {
		in, out := &in.GateParams, &out.GateParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.QueuesConfig != nil {
		in, out := &in.QueuesConfig, &out.QueuesConfig
		*out = make([]AsyncQueueConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncRedisSpec.
func (in *AsyncRedisSpec) DeepCopy() *AsyncRedisSpec {
	if in == nil {
		return nil
	}
	out := new(AsyncRedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncRequestTransform) DeepCopyInto(out *AsyncRequestTransform) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncRequestTransform.
func (in *AsyncRequestTransform) DeepCopy() *AsyncRequestTransform {
	if in == nil {
		return nil
	}
	out := new(AsyncRequestTransform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncTLSSpec) DeepCopyInto(out *AsyncTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncTLSSpec.
func (in *AsyncTLSSpec) DeepCopy() *AsyncTLSSpec {
	if in == nil {
		return nil
	}
	out := new(AsyncTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncTopicConfig) DeepCopyInto(out *AsyncTopicConfig) {
	*out = *in
	if in.GateParams != nil {
		in, out := &in.GateParams, &out.GateParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncTopicConfig.
func (in *AsyncTopicConfig) DeepCopy() *AsyncTopicConfig {
	if in == nil {
		return nil
	}
	out := new(AsyncTopicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncTransformConfig) DeepCopyInto(out *AsyncTransformConfig) {
	*out = *in
	if in.RequestTransforms != nil {
		in, out := &in.RequestTransforms, &out.RequestTransforms
		*out = make([]AsyncRequestTransform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncTransformConfig.
func (in *AsyncTransformConfig) DeepCopy() *AsyncTransformConfig {
	if in == nil {
		return nil
	}
	out := new(AsyncTransformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncWorkerPool) DeepCopyInto(out *AsyncWorkerPool) {
	*out = *in
	if in.GateParams != nil {
		in, out := &in.GateParams, &out.GateParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncWorkerPool.
func (in *AsyncWorkerPool) DeepCopy() *AsyncWorkerPool {
	if in == nil {
		return nil
	}
	out := new(AsyncWorkerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchAPIConfig) DeepCopyInto(out *BatchAPIConfig) {
	*out = *in
	if in.PassThroughHeaders != nil {
		in, out := &in.PassThroughHeaders, &out.PassThroughHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchAPIConfig.
func (in *BatchAPIConfig) DeepCopy() *BatchAPIConfig {
	if in == nil {
		return nil
	}
	out := new(BatchAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentReplicaStatus) DeepCopyInto(out *ComponentReplicaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentReplicaStatus.
func (in *ComponentReplicaStatus) DeepCopy() *ComponentReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(ComponentReplicaStatus)
		**out = **in
	}
	if in.Processor != nil {
		in, out := &in.Processor, &out.Processor
		*out = new(ComponentReplicaStatus)
		**out = **in
	}
	if in.GC != nil {
		in, out := &in.GC, &out.GC
		*out = new(ComponentReplicaStatus)
		**out = **in
	}
	if in.AsyncProcessor != nil {
		in, out := &in.AsyncProcessor, &out.AsyncProcessor
		*out = new(ComponentReplicaStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyConfig) DeepCopyInto(out *ConcurrencyConfig) {
	*out = *in
	if in.AIMD != nil {
		in, out := &in.AIMD, &out.AIMD
		*out = new(AIMDConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyConfig.
func (in *ConcurrencyConfig) DeepCopy() *ConcurrencyConfig {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FSStorageSpec) DeepCopyInto(out *FSStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FSStorageSpec.
func (in *FSStorageSpec) DeepCopy() *FSStorageSpec {
	if in == nil {
		return nil
	}
	out := new(FSStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileAPIConfig) DeepCopyInto(out *FileAPIConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileAPIConfig.
func (in *FileAPIConfig) DeepCopy() *FileAPIConfig {
	if in == nil {
		return nil
	}
	out := new(FileAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRetrySpec) DeepCopyInto(out *FileRetrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRetrySpec.
func (in *FileRetrySpec) DeepCopy() *FileRetrySpec {
	if in == nil {
		return nil
	}
	out := new(FileRetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileStorageSpec) DeepCopyInto(out *FileStorageSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3StorageSpec)
		**out = **in
	}
	if in.FS != nil {
		in, out := &in.FS, &out.FS
		*out = new(FSStorageSpec)
		**out = **in
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(FileRetrySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileStorageSpec.
func (in *FileStorageSpec) DeepCopy() *FileStorageSpec {
	if in == nil {
		return nil
	}
	out := new(FileStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCConfigSpec) DeepCopyInto(out *GCConfigSpec) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCConfigSpec.
func (in *GCConfigSpec) DeepCopy() *GCConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GCConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSpec) DeepCopyInto(out *GCSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(GCConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSpec.
func (in *GCSpec) DeepCopy() *GCSpec {
	if in == nil {
		return nil
	}
	out := new(GCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaSpec) DeepCopyInto(out *GrafanaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaSpec.
func (in *GrafanaSpec) DeepCopy() *GrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(GrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteSpec) DeepCopyInto(out *HTTPRouteSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ParentRefs != nil {
		in, out := &in.ParentRefs, &out.ParentRefs
		*out = make([]ParentReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteSpec.
func (in *HTTPRouteSpec) DeepCopy() *HTTPRouteSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceGatewaySpec) DeepCopyInto(out *InferenceGatewaySpec) {
	*out = *in
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceGatewaySpec.
func (in *InferenceGatewaySpec) DeepCopy() *InferenceGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(InferenceGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBatchGateway) DeepCopyInto(out *LLMBatchGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBatchGateway.
func (in *LLMBatchGateway) DeepCopy() *LLMBatchGateway {
	if in == nil {
		return nil
	}
	out := new(LLMBatchGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMBatchGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBatchGatewayList) DeepCopyInto(out *LLMBatchGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMBatchGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBatchGatewayList.
func (in *LLMBatchGatewayList) DeepCopy() *LLMBatchGatewayList {
	if in == nil {
		return nil
	}
	out := new(LLMBatchGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMBatchGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBatchGatewaySpec) DeepCopyInto(out *LLMBatchGatewaySpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.FileStorage != nil {
		in, out := &in.FileStorage, &out.FileStorage
		*out = new(FileStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.APIServer.DeepCopyInto(&out.APIServer)
	in.Processor.DeepCopyInto(&out.Processor)
	in.GC.DeepCopyInto(&out.GC)
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		**out = **in
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaSpec)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPRoute != nil {
		in, out := &in.HTTPRoute, &out.HTTPRoute
		*out = new(HTTPRouteSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OTEL != nil {
		in, out := &in.OTEL, &out.OTEL
		*out = new(OTELSpec)
		**out = **in
	}
	if in.PrometheusRule != nil {
		in, out := &in.PrometheusRule, &out.PrometheusRule
		*out = new(PrometheusRuleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBatchGatewaySpec.
func (in *LLMBatchGatewaySpec) DeepCopy() *LLMBatchGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(LLMBatchGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBatchGatewayStatus) DeepCopyInto(out *LLMBatchGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComponentStatus != nil {
		in, out := &in.ComponentStatus, &out.ComponentStatus
		*out = new(ComponentStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBatchGatewayStatus.
func (in *LLMBatchGatewayStatus) DeepCopy() *LLMBatchGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(LLMBatchGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTELSpec) DeepCopyInto(out *OTELSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTELSpec.
func (in *OTELSpec) DeepCopy() *OTELSpec {
	if in == nil {
		return nil
	}
	out := new(OTELSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentReference) DeepCopyInto(out *ParentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentReference.
func (in *ParentReference) DeepCopy() *ParentReference {
	if in == nil {
		return nil
	}
	out := new(ParentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorConfigSpec) DeepCopyInto(out *ProcessorConfigSpec) {
	*out = *in
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(ConcurrencyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorConfigSpec.
func (in *ProcessorConfigSpec) DeepCopy() *ProcessorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ProcessorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorSpec) DeepCopyInto(out *ProcessorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GlobalInferenceGateway != nil {
		in, out := &in.GlobalInferenceGateway, &out.GlobalInferenceGateway
		*out = new(InferenceGatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelGateways != nil {
		in, out := &in.ModelGateways, &out.ModelGateways
		*out = make(map[string]InferenceGatewaySpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ProcessorConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AsyncConfig != nil {
		in, out := &in.AsyncConfig, &out.AsyncConfig
		*out = new(AsyncProcessorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorSpec.
func (in *ProcessorSpec) DeepCopy() *ProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(ProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusRuleSpec) DeepCopyInto(out *PrometheusRuleSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusRuleSpec.
func (in *PrometheusRuleSpec) DeepCopy() *PrometheusRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3StorageSpec) DeepCopyInto(out *S3StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3StorageSpec.
func (in *S3StorageSpec) DeepCopy() *S3StorageSpec {
	if in == nil {
		return nil
	}
	out := new(S3StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}
