{{- if and .Values.processor.enabled .Values.processor.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "batch-gateway.processor.fullname" . }}
  labels:
    {{- include "batch-gateway.processor.labels" . | nindent 4 }}
    {{- with .Values.processor.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "batch-gateway.processor.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.processor.podMonitor.interval | quote }}
{{- end }}
