name: Verify Manifest Builds

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/**'
      - 'config/**'
      - 'Makefile'

jobs:
  verify-builds:
    name: Verify kustomize builds
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify manifests
        run: make verify-manifests
